services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pedidosdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pedidos:
    build: ./pedidos
    container_name: pedidos
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: pedidosdb
    depends_on:
      - postgres
    ports:
      - "3001:3000"

  gateway:
    build: ./geteway
    container_name: geteway
    depends_on:
      - pedidos
    ports:
      - "8080:8080"

volumes:
  postgres_data:
